Repository sonalake/design-system, pull requests merged in 2022-02, with the labels that each got.

#40 feat(table): add Table and Pagination Components
  .eslintrc
  .github/workflows/main.yml
  package.json
  src/declarations/react-table-config.d.ts
  src/hooks/index.ts
  src/hooks/use-context-fallback.hook.ts
  src/index.tsx
  src/ui/alert/alert.spec.tsx
  src/ui/alert/alert.stories.tsx
  src/ui/index.ts
  src/ui/pagination/components/index.ts
  src/ui/pagination/components/page-size-select.component.tsx
  src/ui/pagination/components/pages.component.tsx
  src/ui/pagination/components/pagination-button.component.tsx
  src/ui/pagination/components/pagination-dots.component.tsx
  src/ui/pagination/components/pagination-info.component.tsx
  src/ui/pagination/components/pagination-navigation.component.tsx
  src/ui/pagination/components/pagination-range.component.tsx
  src/ui/pagination/components/pagination-results.component.tsx
  src/ui/pagination/context/index.ts
  src/ui/pagination/context/pagination.context.tsx
  src/ui/pagination/index.ts
  src/ui/pagination/pagination.component.tsx
  src/ui/pagination/pagination.model.ts
  src/ui/pagination/pagination.spec.tsx
  src/ui/pagination/pagination.stories.tsx
  src/ui/table/components/index.ts
  src/ui/table/components/table-body.component.tsx
  src/ui/table/components/table-header.component.tsx
  src/ui/table/components/table-loader.component.tsx
  src/ui/table/components/table-sort-icon.component.tsx
  src/ui/table/context/index.ts
  src/ui/table/context/table.context.tsx
  src/ui/table/index.ts
  src/ui/table/table.component.tsx
  src/ui/table/table.model.ts
  src/ui/table/table.spec.tsx
  src/ui/table/table.stories.tsx
  src/ui/table/table.util.ts
  src/ui/tooltip/tooltip.stories.tsx
  yarn.lock
Labels: enhancement

#42 feat(internationalisation): add I18n provider
  package.json
  src/context/formatting/format.constant.ts
  src/context/formatting/formatting.context.tsx
  src/context/formatting/formatting.model.ts
  src/context/formatting/index.ts
  src/context/index.ts
  src/i18n/i18n.component.tsx
  src/i18n/i18n.constant.ts
  src/i18n/i18n.utils.ts
  src/i18n/index.ts
  src/i18n/locales/en.json
  src/i18n/locales/index.ts
  src/i18n/locales/pl.json
  src/index.tsx
  src/ui/alert/alert.spec.tsx
  src/ui/alert/alert.stories.tsx
  src/ui/alert/components/alert-title.component.tsx
  src/ui/label/label.component.tsx
  src/ui/label/label.stories.tsx
  src/ui/pagination/components/pagination-results.component.tsx
  src/ui/pagination/pagination.spec.tsx
  src/ui/pagination/pagination.stories.tsx
  src/ui/property-item/property-item.stories.tsx
  src/ui/table/table.spec.tsx
  src/ui/table/table.stories.tsx
  src/ui/typography/typography.component.tsx
  src/ui/typography/typography.model.ts
  src/ui/typography/typography.spec.tsx
  src/ui/typography/typography.stories.tsx
  src/ui/typography/typography.util.ts
  src/ui/typography/typography.util.tsx
  src/utils/index.ts
  src/utils/test.utils.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement

#38 Feature/text input
  .eslintrc
  src/ui/index.ts
  src/ui/input/index.ts
  src/ui/input/input.model.ts
  src/ui/input/input.util.ts
  src/ui/text-input/index.ts
  src/ui/text-input/text-input.component.tsx
  src/ui/text-input/text-input.spec.tsx
  src/ui/text-input/text-input.stories.tsx
  tailwind.config.js
Labels: enhancement

#44 Feature/formatting
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/context/formatting/formatting.constant.ts
  src/context/formatting/formatting.context.tsx
  src/context/formatting/index.ts
  src/design-system.context.tsx
  src/i18n/i18n.constant.ts
  src/i18n/locales/en.json
  src/i18n/locales/storybook.json
  src/index.tsx
  src/intro.stories.mdx
  src/styles/colors.stories.tsx
  src/ui/date-format/date-format.component.tsx
  src/ui/date-format/date-format.spec.tsx
  src/ui/date-format/date-format.stories.tsx
  src/ui/date-format/index.ts
  src/ui/index.ts
  src/ui/property-item/property-item.stories.tsx
  src/ui/tooltip/tooltip.stories.tsx
  src/utils/test.utils.tsx
  yarn.lock
Labels: enhancement

#50 Feature/notifications
  src/context/design-system.context.tsx
  src/context/index.ts
  src/context/notifications/index.ts
  src/context/notifications/notifications.context.tsx
  src/hooks/index.ts
  src/hooks/use-timeout.hook.ts
  src/i18n/locales/en.json
  src/i18n/locales/storybook.json
  src/index.tsx
  src/intro.component.tsx
  src/intro.stories.mdx
  src/ui/alert/alert.spec.tsx
  src/ui/alert/alert.stories.tsx
  src/ui/button/button.component.tsx
  src/ui/button/button.styles.ts
  src/ui/button/index.ts
  src/ui/index.ts
  src/ui/notification/index.ts
  src/ui/notification/notification-gateway.component.tsx
  src/ui/notification/notification-icon.component.tsx
  src/ui/notification/notification.component.tsx
  src/ui/notification/notification.model.ts
  src/ui/notification/notification.spec.tsx
  src/ui/notification/notification.stories.tsx
  src/ui/pagination/components/pagination-button.component.tsx
  src/ui/stack/index.ts
  src/ui/stack/stack.component.tsx
  src/ui/stack/stack.model.tsx
  src/ui/stack/stack.styles.ts
  src/ui/tooltip/tooltip.spec.tsx
  src/ui/tooltip/tooltip.stories.tsx
  src/ui/typography/typography.model.ts
  src/utils/test.utils.tsx
Labels: enhancement

#53 docs(dev guide): add Developer Guide documentation
  DEV_GUIDE.md
Labels: documentation

#51 feat(checkbox): add checkbox component
  .github/workflows/main.yml
  .storybook/preview.js
  src/hooks/index.ts
  src/hooks/use-element-id.hook.ts
  src/i18n/locales/en.json
  src/i18n/locales/storybook.json
  src/ui/alert/alert.stories.tsx
  src/ui/button/button.stories.tsx
  src/ui/card/card.stories.tsx
  src/ui/checkbox/checkbox.component.tsx
  src/ui/checkbox/checkbox.spec.tsx
  src/ui/checkbox/checkbox.stories.tsx
  src/ui/checkbox/checkbox.styles.ts
  src/ui/checkbox/index.ts
  src/ui/date-format/date-format.stories.tsx
  src/ui/fields/checkbox-field/checkbox-field.component.tsx
  src/ui/fields/checkbox-field/checkbox-field.spec.tsx
  src/ui/fields/checkbox-field/checkbox-field.stories.tsx
  src/ui/fields/checkbox-field/index.ts
  src/ui/fields/checkbox-group-field/checkbox-group-field.component.tsx
  src/ui/fields/checkbox-group-field/checkbox-group-field.spec.tsx
  src/ui/fields/checkbox-group-field/checkbox-group-field.stories.tsx
  src/ui/fields/checkbox-group-field/checkbox-group-model.ts
  src/ui/fields/checkbox-group-field/test-data.constant.ts
  src/ui/fields/index.ts
  src/ui/index.ts
  src/ui/label/label.component.tsx
  src/ui/label/label.stories.tsx
  src/ui/notification/notification.stories.tsx
  src/ui/pagination/pagination.stories.tsx
  src/ui/property-item/property-item.stories.tsx
  src/ui/table/table.stories.tsx
  src/ui/tooltip/tooltip.stories.tsx
  src/ui/typography/typography.stories.tsx
  tailwind.config.js
Labels: enhancement, good first issue
